"""add_topic_questions_and_tag_tables

Revision ID: 12cecc615b4f
Revises: 7578af01d4de
Create Date: 2026-04-22 12:03:07.299173

"""

from __future__ import annotations



from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12cecc615b4f'
down_revision: str | None = '7578af01d4de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_questions',
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('question_text', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_index(op.f('ix_topic_questions_topic_id'), 'topic_questions', ['topic_id'], unique=False)
    op.create_table('question_breeds_link',
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('breed_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['breed_id'], ['breeds.breed_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['topic_questions.question_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id', 'breed_id')
    )
    op.create_table('question_products_link',
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['topic_questions.question_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id', 'product_id')
    )
    op.create_table('question_species_link',
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('species_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['topic_questions.question_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['species_id'], ['pet_species.species_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id', 'species_id')
    )
    op.add_column('topics', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'updated_at')
    op.drop_table('question_species_link')
    op.drop_table('question_products_link')
    op.drop_table('question_breeds_link')
    op.drop_index(op.f('ix_topic_questions_topic_id'), table_name='topic_questions')
    op.drop_table('topic_questions')
    # ### end Alembic commands ###

