"""Add global soft delete tracking

Revision ID: 19187ef08dc4
Revises: d64e390e3496
Create Date: 2026-04-17 10:37:47.975815

"""

from __future__ import annotations



from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19187ef08dc4'
down_revision: str | None = 'd64e390e3496'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_personalities', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('ai_personalities', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('breeds', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('breeds', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('chat_attachments', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('chat_attachments', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('chat_sessions', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('chat_sessions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('messages', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('messages', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('notifications', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('notifications', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pet_species', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('pet_species', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pets', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('pets', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('plans', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('plans', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('product_brands', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('product_brands', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('product_categories', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('product_categories', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('product_recommendations', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('product_recommendations', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('products', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('recommendation_feedback', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('recommendation_feedback', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('roles', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('roles', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('saved_chats', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('saved_chats', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('search_history', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('search_history', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('subscriptions', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('subscriptions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('topics', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('topics', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_preferences', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('user_preferences', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_roles', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('user_roles', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_deleted')
    op.drop_column('user_roles', 'deleted_at')
    op.drop_column('user_roles', 'is_deleted')
    op.drop_column('user_preferences', 'deleted_at')
    op.drop_column('user_preferences', 'is_deleted')
    op.drop_column('topics', 'deleted_at')
    op.drop_column('topics', 'is_deleted')
    op.drop_column('subscriptions', 'deleted_at')
    op.drop_column('subscriptions', 'is_deleted')
    op.drop_column('search_history', 'deleted_at')
    op.drop_column('search_history', 'is_deleted')
    op.drop_column('saved_chats', 'deleted_at')
    op.drop_column('saved_chats', 'is_deleted')
    op.drop_column('roles', 'deleted_at')
    op.drop_column('roles', 'is_deleted')
    op.drop_column('recommendation_feedback', 'deleted_at')
    op.drop_column('recommendation_feedback', 'is_deleted')
    op.drop_column('products', 'deleted_at')
    op.drop_column('products', 'is_deleted')
    op.drop_column('product_recommendations', 'deleted_at')
    op.drop_column('product_recommendations', 'is_deleted')
    op.drop_column('product_categories', 'deleted_at')
    op.drop_column('product_categories', 'is_deleted')
    op.drop_column('product_brands', 'deleted_at')
    op.drop_column('product_brands', 'is_deleted')
    op.drop_column('plans', 'deleted_at')
    op.drop_column('plans', 'is_deleted')
    op.drop_column('pets', 'deleted_at')
    op.drop_column('pets', 'is_deleted')
    op.drop_column('pet_species', 'deleted_at')
    op.drop_column('pet_species', 'is_deleted')
    op.drop_column('notifications', 'deleted_at')
    op.drop_column('notifications', 'is_deleted')
    op.drop_column('messages', 'deleted_at')
    op.drop_column('messages', 'is_deleted')
    op.drop_column('chat_sessions', 'deleted_at')
    op.drop_column('chat_sessions', 'is_deleted')
    op.drop_column('chat_attachments', 'deleted_at')
    op.drop_column('chat_attachments', 'is_deleted')
    op.drop_column('breeds', 'deleted_at')
    op.drop_column('breeds', 'is_deleted')
    op.drop_column('ai_personalities', 'deleted_at')
    op.drop_column('ai_personalities', 'is_deleted')
    # ### end Alembic commands ###

