"""update_chat_sessions_model

Revision ID: 5b2535b6308e
Revises: 12cecc615b4f
Create Date: 2026-04-22 12:30:18.813393

"""

from __future__ import annotations



from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b2535b6308e'
down_revision: str | None = '12cecc615b4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('question_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_chat_sessions_question_id'), 'chat_sessions', ['question_id'], unique=False)
    op.create_foreign_key(None, 'chat_sessions', 'topic_questions', ['question_id'], ['question_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_chat_sessions_question_id'), table_name='chat_sessions')
    op.drop_column('chat_sessions', 'question_id')
    # ### end Alembic commands ###

