"""add_soft_delete_and_metadata_to_product_tables

Revision ID: 7578af01d4de
Revises: 19187ef08dc4
Create Date: 2026-04-22 11:33:03.145114

"""

from __future__ import annotations



from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7578af01d4de'
down_revision: str | None = '19187ef08dc4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_breeds_link',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('breed_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['breed_id'], ['breeds.breed_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'breed_id')
    )
    op.create_table('product_species_link',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('species_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['species_id'], ['pet_species.species_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'species_id')
    )
    op.add_column('product_brands', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('product_brands', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('product_brands', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('product_categories', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('product_categories', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('product_categories', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('product_categories', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('products', 'species_scope')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('species_scope', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('product_categories', 'updated_at')
    op.drop_column('product_categories', 'created_at')
    op.drop_column('product_categories', 'is_active')
    op.drop_column('product_categories', 'image_url')
    op.drop_column('product_brands', 'updated_at')
    op.drop_column('product_brands', 'created_at')
    op.drop_column('product_brands', 'logo_url')
    op.drop_table('product_species_link')
    op.drop_table('product_breeds_link')
    # ### end Alembic commands ###

