"""initial

Revision ID: d64e390e3496
Revises: 
Create Date: 2026-03-20 15:22:58.518596

"""

from __future__ import annotations

from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd64e390e3496'
down_revision: str | None = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_personalities',
    sa.Column('personality_id', sa.Uuid(), nullable=False),
    sa.Column('personality_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tone_style', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('personality_id')
    )
    op.create_index(op.f('ix_ai_personalities_personality_name'), 'ai_personalities', ['personality_name'], unique=True)
    op.create_table('pet_species',
    sa.Column('species_id', sa.Uuid(), nullable=False),
    sa.Column('species_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('species_id')
    )
    op.create_index(op.f('ix_pet_species_species_name'), 'pet_species', ['species_name'], unique=True)
    op.create_table('plans',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('plan_name', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('billing_cycle', sa.String(length=50), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_index(op.f('ix_plans_plan_name'), 'plans', ['plan_name'], unique=True)
    op.create_table('product_brands',
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('brand_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('brand_id')
    )
    op.create_index(op.f('ix_product_brands_brand_name'), 'product_brands', ['brand_name'], unique=True)
    op.create_table('product_categories',
    sa.Column('product_category_id', sa.Uuid(), nullable=False),
    sa.Column('category_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('product_category_id')
    )
    op.create_index(op.f('ix_product_categories_category_name'), 'product_categories', ['category_name'], unique=True)
    op.create_table('roles',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_index(op.f('ix_roles_role_name'), 'roles', ['role_name'], unique=True)
    op.create_table('topics',
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('topic_name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('topic_id')
    )
    op.create_index(op.f('ix_topics_slug'), 'topics', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mobile_number', sa.String(length=30), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('external_auth_id', sa.String(length=255), nullable=True),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('preferred_language', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('mobile_number')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('breeds',
    sa.Column('breed_id', sa.Uuid(), nullable=False),
    sa.Column('species_id', sa.Uuid(), nullable=False),
    sa.Column('breed_name', sa.String(length=100), nullable=False),
    sa.Column('breed_notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['species_id'], ['pet_species.species_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('breed_id'),
    sa.UniqueConstraint('species_id', 'breed_name', name='uq_breeds_species_id_breed_name')
    )
    op.create_index(op.f('ix_breeds_species_id'), 'breeds', ['species_id'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_id_is_read_created_at', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.create_table('products',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('product_category_id', sa.Uuid(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('species_scope', sa.String(length=100), nullable=True),
    sa.Column('life_stage', sa.String(length=100), nullable=True),
    sa.Column('usage_guidelines', sa.Text(), nullable=True),
    sa.Column('ingredients', sa.Text(), nullable=True),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.Column('product_url', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['product_brands.brand_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_category_id'], ['product_categories.product_category_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_products_brand_id'), 'products', ['brand_id'], unique=False)
    op.create_index('ix_products_brand_id_category_id_is_active', 'products', ['brand_id', 'product_category_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_products_product_category_id'), 'products', ['product_category_id'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_table('search_history',
    sa.Column('search_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('search_query', sa.Text(), nullable=False),
    sa.Column('source_page', sa.String(length=200), nullable=False),
    sa.Column('searched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('search_id')
    )
    op.create_index(op.f('ix_search_history_user_id'), 'search_history', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.plan_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subscription_id')
    )
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('preference_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('theme', sa.String(length=50), nullable=True),
    sa.Column('app_language', sa.String(length=20), nullable=True),
    sa.Column('push_notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('default_ai_personality', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('preference_id')
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.create_table('user_roles',
    sa.Column('user_role_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_role_id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_roles_user_id_role_id')
    )
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('pets',
    sa.Column('pet_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('species_id', sa.Uuid(), nullable=False),
    sa.Column('breed_id', sa.Uuid(), nullable=True),
    sa.Column('pet_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('age_in_months', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('is_neutered', sa.Boolean(), nullable=False),
    sa.Column('medical_notes', sa.Text(), nullable=True),
    sa.Column('allergies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dietary_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('activity_level', sa.String(length=50), nullable=True),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['breed_id'], ['breeds.breed_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['species_id'], ['pet_species.species_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pet_id')
    )
    op.create_index(op.f('ix_pets_breed_id'), 'pets', ['breed_id'], unique=False)
    op.create_index(op.f('ix_pets_species_id'), 'pets', ['species_id'], unique=False)
    op.create_index(op.f('ix_pets_user_id'), 'pets', ['user_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('chat_session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('pet_id', sa.Uuid(), nullable=True),
    sa.Column('topic_id', sa.Uuid(), nullable=True),
    sa.Column('personality_id', sa.Uuid(), nullable=True),
    sa.Column('session_title', sa.String(length=200), nullable=False),
    sa.Column('session_type', sa.String(length=50), nullable=False),
    sa.Column('session_summary', sa.Text(), nullable=True),
    sa.Column('is_general_chat', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['personality_id'], ['ai_personalities.personality_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.pet_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_session_id')
    )
    op.create_index(op.f('ix_chat_sessions_personality_id'), 'chat_sessions', ['personality_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_pet_id'), 'chat_sessions', ['pet_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_topic_id'), 'chat_sessions', ['topic_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_index('ix_chat_sessions_user_id_started_at_last_message_at', 'chat_sessions', ['user_id', 'started_at', 'last_message_at'], unique=False)
    op.create_table('messages',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('chat_session_id', sa.Uuid(), nullable=False),
    sa.Column('sender_user_id', sa.Uuid(), nullable=True),
    sa.Column('sender_type', sa.String(length=50), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('contains_recommendation', sa.Boolean(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.chat_session_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('message_id'),
    sa.UniqueConstraint('chat_session_id', 'sequence_number', name='uq_messages_chat_session_id_sequence_number')
    )
    op.create_index(op.f('ix_messages_chat_session_id'), 'messages', ['chat_session_id'], unique=False)
    op.create_index('ix_messages_chat_session_id_sequence_number_created_at', 'messages', ['chat_session_id', 'sequence_number', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_sender_user_id'), 'messages', ['sender_user_id'], unique=False)
    op.create_table('saved_chats',
    sa.Column('saved_chat_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('chat_session_id', sa.Uuid(), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.chat_session_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('saved_chat_id'),
    sa.UniqueConstraint('user_id', 'chat_session_id', name='uq_saved_chats_user_id_chat_session_id')
    )
    op.create_index(op.f('ix_saved_chats_chat_session_id'), 'saved_chats', ['chat_session_id'], unique=False)
    op.create_index(op.f('ix_saved_chats_user_id'), 'saved_chats', ['user_id'], unique=False)
    op.create_table('chat_attachments',
    sa.Column('attachment_id', sa.Uuid(), nullable=False),
    sa.Column('chat_session_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.chat_session_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.message_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    op.create_index(op.f('ix_chat_attachments_chat_session_id'), 'chat_attachments', ['chat_session_id'], unique=False)
    op.create_index(op.f('ix_chat_attachments_message_id'), 'chat_attachments', ['message_id'], unique=False)
    op.create_table('product_recommendations',
    sa.Column('recommendation_id', sa.Uuid(), nullable=False),
    sa.Column('chat_session_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('pet_id', sa.Uuid(), nullable=True),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('recommendation_reason', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('recommendation_type', sa.String(length=50), nullable=True),
    sa.Column('user_clicked', sa.Boolean(), nullable=False),
    sa.Column('user_saved', sa.Boolean(), nullable=False),
    sa.Column('user_purchased', sa.Boolean(), nullable=False),
    sa.Column('recommended_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.chat_session_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.message_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.pet_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    op.create_index('ix_pr_chat_session_product_recommended', 'product_recommendations', ['chat_session_id', 'product_id', 'recommended_at'], unique=False)
    op.create_index(op.f('ix_product_recommendations_chat_session_id'), 'product_recommendations', ['chat_session_id'], unique=False)
    op.create_index(op.f('ix_product_recommendations_message_id'), 'product_recommendations', ['message_id'], unique=False)
    op.create_index(op.f('ix_product_recommendations_pet_id'), 'product_recommendations', ['pet_id'], unique=False)
    op.create_index(op.f('ix_product_recommendations_product_id'), 'product_recommendations', ['product_id'], unique=False)
    op.create_table('recommendation_feedback',
    sa.Column('feedback_id', sa.Uuid(), nullable=False),
    sa.Column('recommendation_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('was_helpful', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['product_recommendations.recommendation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_index(op.f('ix_recommendation_feedback_recommendation_id'), 'recommendation_feedback', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_recommendation_feedback_user_id'), 'recommendation_feedback', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_feedback_user_id'), table_name='recommendation_feedback')
    op.drop_index(op.f('ix_recommendation_feedback_recommendation_id'), table_name='recommendation_feedback')
    op.drop_table('recommendation_feedback')
    op.drop_index(op.f('ix_product_recommendations_product_id'), table_name='product_recommendations')
    op.drop_index(op.f('ix_product_recommendations_pet_id'), table_name='product_recommendations')
    op.drop_index(op.f('ix_product_recommendations_message_id'), table_name='product_recommendations')
    op.drop_index(op.f('ix_product_recommendations_chat_session_id'), table_name='product_recommendations')
    op.drop_index('ix_pr_chat_session_product_recommended', table_name='product_recommendations')
    op.drop_table('product_recommendations')
    op.drop_index(op.f('ix_chat_attachments_message_id'), table_name='chat_attachments')
    op.drop_index(op.f('ix_chat_attachments_chat_session_id'), table_name='chat_attachments')
    op.drop_table('chat_attachments')
    op.drop_index(op.f('ix_saved_chats_user_id'), table_name='saved_chats')
    op.drop_index(op.f('ix_saved_chats_chat_session_id'), table_name='saved_chats')
    op.drop_table('saved_chats')
    op.drop_index(op.f('ix_messages_sender_user_id'), table_name='messages')
    op.drop_index('ix_messages_chat_session_id_sequence_number_created_at', table_name='messages')
    op.drop_index(op.f('ix_messages_chat_session_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_chat_sessions_user_id_started_at_last_message_at', table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_topic_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_pet_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_personality_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_pets_user_id'), table_name='pets')
    op.drop_index(op.f('ix_pets_species_id'), table_name='pets')
    op.drop_index(op.f('ix_pets_breed_id'), table_name='pets')
    op.drop_table('pets')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_search_history_user_id'), table_name='search_history')
    op.drop_table('search_history')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_product_category_id'), table_name='products')
    op.drop_index('ix_products_brand_id_category_id_is_active', table_name='products')
    op.drop_index(op.f('ix_products_brand_id'), table_name='products')
    op.drop_table('products')
    op.drop_index('ix_notifications_user_id_is_read_created_at', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_breeds_species_id'), table_name='breeds')
    op.drop_table('breeds')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_topics_slug'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_roles_role_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_product_categories_category_name'), table_name='product_categories')
    op.drop_table('product_categories')
    op.drop_index(op.f('ix_product_brands_brand_name'), table_name='product_brands')
    op.drop_table('product_brands')
    op.drop_index(op.f('ix_plans_plan_name'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_pet_species_species_name'), table_name='pet_species')
    op.drop_table('pet_species')
    op.drop_index(op.f('ix_ai_personalities_personality_name'), table_name='ai_personalities')
    op.drop_table('ai_personalities')
    # ### end Alembic commands ###

