$kind: http-request
name: Get OpenAPI Docs
method: GET
url: '{{base_url}}/openapi.json'
order: 2000
scripts:
  - type: afterResponse
    language: text/javascript
    code: |-
      pm.test("Status code is 200", function () {
          pm.response.to.have.status(200);
      });

      pm.test("Response is valid OpenAPI spec", function () {
          const jsonData = pm.response.json();
          pm.expect(jsonData).to.have.property("openapi");
          pm.expect(jsonData).to.have.property("info");
          pm.expect(jsonData).to.have.property("paths");
      });

      pm.test("API info is present", function () {
          const jsonData = pm.response.json();
          pm.expect(jsonData.info).to.have.property("title");
          pm.expect(jsonData.info).to.have.property("version");
      });
